title: <p align="center"> Nurlita Kholishotunnisa </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nurlitaakho/">LinkedIn</a> |
  <a href="https://github.com/nurlitaakho">GitHub</a>
  </p>
  
  <p align="justify">
  I am currently a 6th Semester Student at Diponegoro University Majoring in Statistics
  <br><br>
  I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
